"""empty message

Revision ID: 6f60fa5ce35f
Revises: 913382131dd9
Create Date: 2019-03-15 13:31:57.844225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f60fa5ce35f'
down_revision = '913382131dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('attach_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('length(type) < 256', name='attachments_type_check'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name='attachments_chat_id_fkey'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], name='attachments_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='attachments_user_id_fkey'),
    sa.PrimaryKeyConstraint('attach_id', name='attachments_pkey')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nick', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('length(name) < 32', name='users_name_check'),
    sa.CheckConstraint('length(name) < 32', name='users_name_check1'),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('nick', name='users_nick_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('passwords',
    sa.Column('password_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='passwords_user_id_fkey')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.INTEGER(), server_default=sa.text("nextval('chats_chat_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('is_group_chat', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('length(last_message) < 32', name='chats_last_message_check'),
    sa.CheckConstraint('length(topic) < 256', name='chats_topic_check'),
    sa.PrimaryKeyConstraint('chat_id', name='chats_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('messages',
    sa.Column('message_id', sa.INTEGER(), server_default=sa.text("nextval('messages_message_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('length(content) < 65536', name='messages_content_check'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name='messages_chat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('message_id', name='messages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('members',
    sa.Column('member_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_messages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_read_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name='members_chat_id_fkey'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.message_id'], name='last_read_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='members_user_id_fkey'),
    sa.PrimaryKeyConstraint('member_id', name='members_pkey')
    )
    op.drop_table('member')
    # ### end Alembic commands ###
